Http/routes.php
<?php



Route::group(['middleware' => ['web']], function () {
    Route::group(array("prefix" => "admin", "as"=>"admin."), function () {
        Route::group(['middleware' => 'auth:dcms'], function () {

                //ARTICLES
            Route::group(array("prefix" => "articles" ,"as"=>"articles."), function () {
                Route::get('{id}/copy', array('as'=>'copy', 'uses' => 'ArticleController@copy'));
                Route::get('articlerelation/{article_id?}', array('as'=>'articlerelation', 'uses' => 'ArticleController@getArticleRelation'));

                //CATEGORIES
                Route::group(array("prefix" => "categories", "as"=>"categories."), function () {
                    Route::get('{id}/copy', array('as'=>'{id}.copy', 'uses' => 'CategoryController@copy'));
                    Route::any('api/table', array('as'=>'api.table', 'uses' => 'CategoryController@getDatatable'));
                });
                Route::resource('categories', 'CategoryController');

                //API
                Route::group(array("prefix" => "api", "as"=>"api."), function () {
                    Route::any('table', array('as'=>'table', 'uses' => 'ArticleController@getDatatable'));
                });
            });
            Route::resource('articles', 'ArticleController');
        });
    });
});

Http/Controllers/ArticleController.php
<?php

namespace Dcms\Articles\Http\Controllers;

use Dcms\Articles\Models\Article;
use Dcms\Articles\Models\ArticleToArticle;
use Dcms\Articles\Models\Detail;
use Dcms\Articles\Models\Category;

//use Dcweb\Dcms\Models\Pages\Page;
//use Dcweb\Dcms\Controllers\Pages\PageController;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use View;
use Input;
use Session;
use Validator;
use Redirect;
use DB;
use DataTables;
use Auth;
use Form;
use DateTime;

class ArticleController extends Controller
{
    public $article_language_Columnnames = [];
    public $article_Columnnames = [];

    public $articlelanguageFormTemplate = "";
    public $articleFormTemplate = "";

    public $extendgeneralTemplate = "";

    public function __construct()
    {
        $this->middleware('permission:articles-browse')->only('index');
        $this->middleware('permission:articles-add')->only(['create', 'store']);
        $this->middleware('permission:articles-edit')->only(['edit', 'update']);
        $this->middleware('permission:articles-delete')->only('destroy');

        //note startdate and enddate are defaults, since these are always there, and have a specific value (not simple text, or bool)
        $this->article_Columnnames = [
            'thumbnail'     => 'thumbnail',
            'enabletime'    => 'enabletime',
            'birthdaycycle' => 'birthdaycycle',
            'highpriority'  => 'highpriority',
            'online'        => 'online',
            'newarticle'    => 'newarticle',
            'calendar'      => 'calendar',
            'archive'       => 'archive',
        ];

        $this->article_language_Columnnames = [
            'article_category_id' => 'category_id',
            'title'               => 'title',
            'description'         => 'description',
            'body'                => 'body',
            'slug'                => 'title',
            'path'                => 'title',
            'url'                 => 'url',
        ];

        $this->articlelanguageFormTemplate = null;
        $this->articleFormTemplate = null;
    }

    public static function getArticlesDetailByLanguage($language_id = null)
    {
        return Detail::where("language_id", "=", $language_id)->lists("title", "id");
    }

    public static function getDropdownArticlesByLanguage($language_id = null)
    {
        $dropdownvalues = ArticleController::getArticlesDetailByLanguage($language_id);

        return Form::select("article[" . $language_id . "][]", $dropdownvalues, [3, 4, 5, 6], ["id" => "articles-" . $language_id, "multiple" => "multiple"]);
    }


    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        // load the view
        return View::make('dcms::articles/index');
    }


    public function getDatatable()
    {
        return DataTables::queryBuilder(
            DB::connection('project')
                ->table('articles')
                ->select(
                    'articles.id',
                    'articles_language.title',
                    'articles_language.id as article_language_id',
                    'articles_categories_language.title as category',
                    (DB::connection("project")->raw('Concat("<img src=\'/packages/dcms/core/images/flag-",lcase(country),".png\' >") as country'))
                )
                ->join('articles_language', 'articles.id', '=', 'articles_language.article_id')
                ->leftJoin('articles_categories_language', 'articles_categories_language.id', '=', 'articles_language.article_category_id')
                ->leftJoin('languages', 'articles_language.language_id', '=', 'languages.id')
        )
            ->addColumn('edit', function ($model) {
                $edit = '<form method="POST" action="/admin/articles/' . $model->article_language_id . '" accept-charset="UTF-8" class="pull-right">
								<input name="_token" type="hidden" value="' . csrf_token() . '">
								<input name="_method" type="hidden" value="DELETE">';
                if (Auth::user()->can('articles-edit')) {
                    $edit .= '<a class="btn btn-xs btn-default" href="/admin/articles/' . $model->id . '/edit"><i class="far fa-pencil"></i></a>';
                }
                if (Auth::user()->can('articles-add')) {
                    $edit .= '<a class="btn btn-xs btn-default" href="/admin/articles/' . $model->article_language_id . '/copy"><i class="far fa-copy"></i></a>';
                }
                if (Auth::user()->can('articles-delete')) {
                    $edit .= '<button class="btn btn-xs btn-default" type="submit" value="Delete this article" onclick="if(!confirm(\'Are you sure to delete this item ? \')){return false;};"><i class="far fa-trash-alt"></i></button>';
                }
                $edit .= '</form>';

                return $edit;
            })
            ->rawColumns(['country', 'edit'])
            ->make(true);
    }

    public function getInformation($id = null)
    {
        if (is_null($id)) {
            return DB::connection("project")->table("languages")->select((DB::connection("project")->raw("'' as title, NULL as sort_id, (select max(sort_id) from articles_language where language_id = languages.id) as maxsort, '' as description , '' as body, '' as url, '' as article_category_id, '' as id")), "id as language_id", "language", "country", "language_name")->get();
        } else {
            return DB::connection("project")->select('
													SELECT language_id, languages.language, languages.country, languages.language_name, article_category_id, articles_language.id, article_id, title, sort_id, (select max(sort_id) from articles_language as X  where X.language_id = articles_language.language_id) as maxsort,  description, body, url, date_format(startdate,\'%d-%m-%Y\') as startdate , date_format(enddate,\'%d-%m-%Y\')  as enddate
													FROM articles_language
													LEFT JOIN languages on languages.id = articles_language.language_id
													LEFT JOIN articles on articles.id = articles_language.article_id
													WHERE  languages.id is not null AND  article_id = ?
													UNION
													SELECT languages.id , language, country, language_name, \'\' , \'\' ,  \'\' , \'\' , NULL as sort_id, (select max(sort_id) from articles_language where language_id = languages.id) as maxsort, \'\' , \'\'  , \'\' , \'\' , \'\'
													FROM languages
													WHERE id NOT IN (SELECT language_id FROM articles_language WHERE article_id = ?) ORDER BY 1
													', [$id, $id]);
        }
    }

    public function getExtendedModel()
    {
        //do nothing let the extend class hook into this
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $languages = $this->getInformation();

        // load the create form (app/views/articles/create.blade.php)
        return View::make('dcms::articles/form')
            ->with('languages', $languages)
            ->with('categoryOptionValues', Category::OptionValueTreeArray(false))
            ->with('pageOptionValuesSelected', [])
            ->with('sortOptionValues', $this->getSortOptions($languages, 1))
            ->with('articlelanguageFormTemplate', $this->articlelanguageFormTemplate)
            ->with('articleFormTemplate', $this->articleFormTemplate)
            ->with('extendgeneralTemplate', ['template' => $this->extendgeneralTemplate, 'model' => $this->getExtendedModel()]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $article = Article::find($id);
        $cat = $article->category;

        // show the view and pass the nerd to it
        return View::make('dcms::articles/show')
            ->with('article', $article)
            ->with("category", $cat->title);
    }

    public function getSortOptions($model, $setExtra = 0)
    {
        foreach ($model as $M) {
            $increment = 0;
            if ($setExtra > 0) {
                $increment = $setExtra;
            }
            if (intval($M->id) <= 0 && !is_null($M->maxsort)) {
                $increment = 1;
            }

            $maxSortID = $M->maxsort;
            if (is_null($maxSortID)) {
                $maxSortID = 1;
            }

            for ($i = 1; $i <= ($maxSortID + $increment); $i++) {
                $SortOptions[$M->language_id][$i] = $i;
            }
        }

        return $SortOptions;
    }

    public function getSelectedPages($articleid = null)
    {
        return DB::connection("project")->select('  SELECT article_detail_id, page_id
													FROM articles_language_to_pages
													WHERE article_detail_id IN (SELECT id FROM articles_language WHERE article_id = ?)', [$articleid]);
    }

    public function setPageOptionValues($objselected_pages)
    {
        $pageOptionValuesSelected = [];
        if (count($objselected_pages) > 0) {
            foreach ($objselected_pages as $obj) {
                $pageOptionValuesSelected[$obj->page_id] = $obj->page_id;
            }
        }

        return $pageOptionValuesSelected;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $article = Article::find($id);
        $article->startdate = (is_null($article->startdate) ? null : DateTime::createFromFormat('Y-m-d', $article->startdate)->format('m/d/Y'));
        $article->enddate = (is_null($article->enddate) ? null : DateTime::createFromFormat('Y-m-d', $article->enddate)->format('m/d/Y'));

        $objlanguages = $this->getInformation($id);
        $objselected_pages = $this->getSelectedPages($id);

        return View::make('dcms::articles/form')

resources/views/articles/index.blade.php
@extends("dcms::template/layout")

@section("content")

    <div class="main-header">
        <h1>Articles</h1>
        <ol class="breadcrumb">
            <li><a href="{!! URL::to('admin/dashboard') !!}"><i class="far fa-tachometer-alt-average"></i> Dashboard</a></li>
            <li class="active"><i class="fa fa-pencil"></i> Articles</li>
        </ol>
    </div>

    <div class="main-content">
        <div class="row">
            <div class="col-md-12">
                <div class="main-content-block">

                    @if (Session::has('message'))
                        <div class="alert alert-info">{!! Session::get('message') !!}</div>
                    @endif

                    @can('articles-add')
                        <div class="btnbar btnbar-right"><a class="btn btn-small btn-primary" href="{!! URL::to('/admin/articles/create') !!}">Create new</a></div>
                    @endcan

                    <h2>Overview</h2>

                    <table id="datatable" class="table table-hover table-condensed" style="width:100%">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Title</th>
                            <th style="width:200px;">Category</th>
                            <th>Country</th>
                            <th></th>
                        </tr>
                        </thead>
                    </table>

                    <script type="text/javascript">
                        $(document).ready(function () {
                            oTable = $('#datatable').DataTable({
                                "pageLength": 50,
                                "processing": true,
                                "serverSide": true,
                                "ajax": "{{ route('admin.articles.api.table') }}",
                                "columns": [
                                    {data: 'id', name: 'ID'},
                                    {data: 'title', name: 'articles_language.title'},
                                    {data: 'category', name: 'articles_categories_language.title'},
                                    {data: 'country', name: 'country', searchable: false},
                                    {data: 'edit', name: 'edit', orderable: false, searchable: false}
                                ]
                            });
                        });
                    </script>


                    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.css">

                    <script type="text/javascript" language="javascript" src="//cdn.datatables.net/1.10.0/js/jquery.dataTables.min.js"></script>
                    <script type="text/javascript" language="javascript"
                            src="//cdn.datatables.net/plug-ins/be7019ee387/integration/bootstrap/3/dataTables.bootstrap.js"></script>

                </div>
            </div>
        </div>
    </div>

@stop